### ISSUE TITLE
Security of sensitive data

### ISSUE THREAD

**Issue by coxy17** [divengine/div-ajax-mapping#2]
Hi

I am looking to use this in a small project but just wanted to know is there any security risks with passing sensitive data between PHP and JS using ajaxmap. Are you using the JS fetch API or XMLHttpRequest? 

thanks

Nick

**Comment by coxy17** [comment]
also get this warning in Firefox developer console "XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help https://xhr.spec.whatwg.org/#sync-warning".

**Comment by coxy17** [comment]
sorry for another message, i also receive the following error when testing

_Fatal error: Uncaught ArgumentCountError: Too few arguments to function divengine\ajaxmap::__construct(), 0 passed in C:\wamp\www\teststuff\divengine-ajaxmap\test.php on line 24 and exactly 1 expected in C:\wamp\www\teststuff\divengine-ajaxmap\vendor\divengine\ajaxmap\src\ajaxmap.php on line 52_

php file
```
use divengine\ajaxmap;
require __DIR__ . '/vendor/autoload.php';

function sum($x, $y){
  return $x + $y; 
}

class Enterprise{
  public static function getEmployees(){
      return [
        ["name" => "Thomas Hardy", "salary" => 1500],  
        ["name" => "Christina Berglund", "salary" => 1200] 
      ];  
    } 
}

// Server instance ...

$server = new ajaxmap(); 

// ... Add methods ...

$server->addMethod("sum"); 
$server->addClass("Enterprise"); 

// ... and go!
$server->go(); 
```

html

```
<!DOCTYPE html>
<html>
<head>
<title>Divengine Ajaxmap</title>
<meta name="viewport" content="width=device-width, user-scalable=no">
</head>
<body>

<h1>Test Ajaxmap</h1>

<script type="text/javascript" src="http://localhost/teststuff/divengine-ajaxmap/vendor/divengine/ajaxmap/ajaxmap.js"></script>
<script type="text/javascript">
    var map = new ajaxmap("test.php");
    var sum = map.sum(20, 10);
  
	
	console.log(sum);

</script>

</body>
</html>
```

**Comment by rafageist** [comment]
Hello

I'm working on version 2.0 in the `develop` branch which will have important changes and modernization.

Regards

**Comment by coxy17** [comment]
ok sounds great thanks!
